### ISSUE TITLE
关于使用项目中 python test_udp.py的指令后出现错误的后续问题请教

### ISSUE THREAD

**Issue by h-yy-bag** [Ruby-He/ProTegO#2]
原命令中好像缺失了一个"/" 
修改后的命令为： python test_udp.py --output res-XX --str_model STR_modules/downloads_models/CRNN-None-VGG-BiLSTM-CTC-sensitive.pth --STR_name CRNN --Transformation None --FeatureExtraction VGG --SequenceModeling BiLSTM --Prediction CTC

出现下列问题
Loading a STR model from "STR_modules/downloads_models/CRNN-None-VGG-BiLSTM-CTC-sensitive.pth" as the target model!
***********Test Finished !***********
Traceback (most recent call last):
  File "test_udp.py", line 228, in <module>
    test_udp(opt, device, adv_output_path1, adv_output_path2, test_output_path)
  File "test_udp.py", line 156, in test_udp
    psr1 = asc1 / len(test_dataset1)
ZeroDivisionError: division by zero
出现了该报错，请问是什么原因呢

**Comment by xiguala123** [comment]
Hi, I had this problem too, have you solved it yet?

**Comment by h-yy-bag** [comment]
well i think i finished   we should change the "res-xx" with the train results we got in last step(white box test)

**Comment by h-yy-bag** [comment]
> python test_udp.py --output res-XX --str_model STR_modules/downloads_models/CRNN-None-VGG-BiLSTM-CTC-sensitive.pth --STR_name CRNN --Transformation None --FeatureExtraction VGG --SequenceModeling BiLSTM --Prediction CTC

![image](https://github.com/Ruby-He/ProTegO/assets/77529225/babb1390-506a-421b-ab4e-b9544ba9592e)
